paths:
  yaml: "../src/config.yaml"
  raw: "../data/raw/Telco_data.csv"
  processed: "../data/processed/telco_preprocessed.csv"
  nofiber: "../data/processed/nf_clients.csv"
  fiber_prob: "../data/processed/fiber_prob.csv"
  model_fiber: "../models/fiber.pkl"
  preprocessor: "../models/preprocessor.pkl"
  predictions: "../data/predictions/"

data_standardization:
  "Yes": "Yes"
  "No":
    - "No"
    - "No internet service"
    - "No phone service"
  "male": "Male"
  "female": "Female"
  "fiber_optic": "Fiber optic"
  "month_to_month": "Month-to-month"
  "one_year": "One year"
  "two_year": "Two year"
  "electronic_check": "Electronic check"
  "mailed_check": "Mailed check"
  "bank_transfer": "Bank transfer (automatic)"
  "credit_card": "Credit card (automatic)"
  

mapping:
  cltv: "CLTV"
  contract_type: "Contract"
  customer_id: "CustomerID"
  dependents: "Dependents"
  device_protection: "Device Protection"
  gender: "Gender"
  internet_service: "Internet Service"
  multiple_lines: "Multiple Lines"
  online_backup: "Online Backup"
  online_security: "Online Security"
  paperless_billing: "Paperless Billing"
  partner: "Partner"
  payment_method: "Payment Method"
  phone_service: "Phone Service"
  senior_citizen: "Senior Citizen"
  streaming_movies: "Streaming Movies"
  streaming_tv: "Streaming TV"
  tech_support: "Tech Support"
  tenure_months: "Tenure Months"

features:
  n_features_to_select: 18

  numerical_features:
    - "tenure_months"
    - "cltv"

  ordinal_categoricals:
    - "contract_type"

  nominal_categoricals:
    - "gender"
    - "senior_citizen"
    - "partner"
    - "dependents"
    - "phone_service"
    - "multiple_lines"
    - "online_security"
    - "online_backup"
    - "device_protection"
    - "tech_support"
    - "streaming_tv"
    - "streaming_movies"
    - "paperless_billing"
    - "payment_method"
  ordinal_orders:
    - ["month_to_month", "one_year", "two_year"]


  columns_ord_shap: ['ord__contract_type',
 'nom__phone_service_yes',
 'num__tenure_months',
 'nom__multiple_lines_yes',
 'nom__streaming_tv_yes',
 'nom__streaming_movies_yes',
 'nom__paperless_billing_yes',
 'nom__payment_method_electronic_check',
 'nom__payment_method_mailed_check',
 'nom__device_protection_yes',
 'nom__senior_citizen_yes',
 'num__cltv',
 'nom__tech_support_yes',
 'nom__online_backup_yes',
 'nom__online_security_yes',
 'nom__dependents_yes',
 'nom__partner_yes',
 'nom__gender_male',
 'nom__payment_method_credit_card']

  extra_services:
    - "phone_service"
    - "multiple_lines"
    - "online_security"
    - "online_backup"
    - "device_protection"
    - "streaming_tv"
    - "streaming_movies"

  useless_columns:
    - "Count"
    - "Country"
    - "State"
    - "City"
    - "Zip Code"
    - "Lat Long"
    - "Latitude"
    - "Longitude"
    - "Churn Value"
    - "Churn Score"
    - "Churn Label"
    - "Churn Reason"
    - "Monthly Charges"
    - "Total Charges"
