paths:
  raw: "../data/raw/Telco_data.csv"
  processed: "../data/processed/"
  nofiber: "../data/processed/nf_clients.csv"
  fiber_prob: "../data/processed/fiber_prob.csv"
  model: "../models/random_forest_final.pkl"


features:
  optimized_columns:
    - "CLTV"
    - "Tenure Months"
    - "Total Extra Services"
    - "Payment Method"
    - "Multiple Lines"
    - "Contract"
    - "Streaming TV"
    - "Phone Service"
    - "Paperless Billing"
    - "Streaming Movies"
    - "Senior Citizen"
    - "Tech Support"
    - "Online Security"

  nofiber_columns:
    - "CustomerID"
    - "CLTV"
    - "Tenure Months"
    - "Total Extra Services"
    - "Payment Method"
    - "Multiple Lines"
    - "Contract"
    - "Streaming TV"
    - "Phone Service"
    - "Paperless Billing"
    - "Streaming Movies"
    - "Senior Citizen"
    - "Tech Support"
    - "Online Security"

  extra_services:
    - "Phone Service"
    - "Multiple Lines"
    - "Online Security"
    - "Online Backup"
    - "Device Protection"
    - "Streaming TV"
    - "Streaming Movies"

  useless_columns:
    - "Count"
    - "Country"
    - "State"
    - "City"
    - "Zip Code"
    - "Lat Long"
    - "Latitude"
    - "Longitude"
    - "Churn Value"
    - "Churn Score"
    - "Churn Label"
    - "Churn Reason"
    - "Monthly Charges"
    - "Total Charges"
